### PR TITLE
Changes to Authentication, Repo API and User API

### PR DESCRIPTION
**Pull request by rolfvandekrol**
I changed the authentication logic a little (backward compatibility maintained) to allow authentication using the HTTP Basic Authentication. According to the Github API documentation (http://develop.github.com/p/general.html), the currently used authentication method, of passing username and token around in the url, is deprecated.
I did quite a lot changes to the Repo API to add all the missing methods that are documented in http://develop.github.com/p/repo.html. Furthermore I changed the existing documentation links to the new location, because the documentation seems to have been moved. The third thing I did was moving some methods around, to get a more logical ordering of the methods.
To the User API I added the Public Key Management methods.

I hope that you will incorporate these changes into your repository.

PS1: I didn't yet write tests for the new methods. 
PS2: I'm planning to do the same for the other methods, so be prepared for some more pull requests :P

### CODE REVIEW

**Comment by rolfvandekrol** [comment]
Hmm, nevermind for a while. I'm writing the tests now, and some changes definitely need some love still. Will come back to you when the tests are done and passing yolly good.

**Comment by ornicar** [comment]
Yay, looks very cool. Having tests would be better for sure. Keep me updated, thanks!

**Comment by ornicar** [comment]
I merged your commits. Thanks a lot for your work.
Now documentation needs to be updated to mention the new methods. Could you handle that too, please?

**Comment by rolfvandekrol** [comment]
I'm working on it.

**Pull request merged**
