### PR TITLE
Version doesn't automatically pick up in composer.

### PR DESCRIPTION
**Pull request by frankcarey**
...automatically (X.Y.Z). This is set to NEXT version number.

Alternative is to just use the X.Y.Z format on the next release, so "3.3.0" See http://packagist.org/about

The way to get around it for now if you want to include this package, is to set version to "*" in the require.

### CODE REVIEW

**Comment by ornicar** [comment]
thanks!

**Comment by frankcarey** [comment]
Yeah, I have some code that resolved that too... (could only use *). Composer looks for X.Y.Z ...

http://packagist.org/about

So can we do "4.x" branch so that those using " \* " are still ok for now?  to use that I think the version would be "dev-4.x", and the first full release would be "4.1.0" ?  We should put out that using " \* " is deprecated though and create a proper releases in the full format... "3.2.0" or at least a "3.x" branch? My 5a26f61 commit set the tag specifically, but if the branches / tags are done this way , I think it becomes automatic.

**Comment by frankcarey** [comment]
@ornicar - can you make the new "4.x" branch when you have a minute? Also a "3.x" branch and a 3.3.0 tag so that people can start using that instead of master? (Not sure why the other branches don't get picked up.... per the composer doc they should.

**Comment by ornicar** [comment]
done!

**Pull request merged**
