### PR TITLE
Initial pass at adding support for Composer

### PR DESCRIPTION
**Pull request by simensen**
Initial pass at adding support for Composer. This will hopefully be enough to get into packagist with a master-dev version. Future tags will be accessible by version numbers if this project continues to use the same naming scheme for tags that it has been using.

I went with `ornicar/github-api` for the package name. I thought `php` might be redundant given composer is really just for PHP packages.
- http://getcomposer.org/
- http://packagist.org/

### CODE REVIEW

**Comment by simensen** [comment]
Thanks for the merge, ornicar. Would you be able to create an account on http://packagist.org/ and submit this repository? That will finish the process of getting php-github-api listed as a composer installable package.

If you'd like help maintaining the relationship with packagist I'd be happy to help maintain that aspect of it. Let me know!

Thanks again. :)

**Comment by ornicar** [comment]
I'd appreciate if you deal with packagist from A to Z :) I'm not doing PHP anymore and I never used packagist.

Thanks for contributing!

**Comment by simensen** [comment]
Sounds good, added! http://packagist.org/packages/ornicar/github-api

The only thing I might need to bother you about in the future RE: packagist would be adding an eventual GitHub hook once packagist supports it. This will enable packagist to collect new information as it is sent to GitHub. (new tags, updates to branches, etc.) That might be another few weeks/months, though. :)

**Comment by ornicar** [comment]
No problem, ping me later

**Pull request merged**
